FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY start_app.py .
COPY app/ ./app/

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1
ENV PORT=8000
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8000

CMD ["python", "start_app.py"]