app = "scraping-natal-prefeitura"
primary_region = "gru"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true

[deploy]
  release_command = "python -c 'print(\"API mode only - Scraper disabled\")';"

[processes]
  app = "python main.py --api-only"