app = "scraping-natal-prefeitura"
primary_region = "gru"  # São Paulo, Brasil

[build]
  dockerfile = "docker/Dockerfile"  

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1