app = "scraping-natal-prefeitura"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  POSTGRES_CONNECTION_STRING = "postgresql://postgres:postgres@localhost:5432/natal_prefeitura"

[http_service]
  internal_port = 8000
  force_https = true