app = "scraping-natal-prefeitura"
primary_region = "gru"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  processes = ["app"]

[deploy]
  release_command = "python -c 'print(\"API mode only - Scraper disabled\")'"

[[processes]]
  name = "app"
  cmd = "python fly_app.py"
  memory = 256